### ISSUE TITLE
Exception in password reset view

### ISSUE THREAD

**Issue by roengraft** [stormpath/stormpath-flask#25]
Hi, 

It seems like the format of StormpathException objects has changed in a recent update to the stormpath module for python? I'm using stompath==1.3.5 and Flask-Stormpath==0.3.6 and get the following error when I submit a password reset request for an unknown email address:

    Traceback (most recent call last):
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/vagrant/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/vagrant/env/lib/python2.7/site-packages/flask_stormpath/views.py", line 164, in forgot
        if 'https' in err.message.lower():
    AttributeError: 'dict' object has no attribute 'lower'

If I inspect the err.message object in the debugger, I see the following representation:

    {u'status': 400, u'developerMessage': u"The email property value 'aoeu@aeou.com' does not match a known resour  , u'message': u"The email property value 'aoeu@aeou.com' does not match a known resour  , u'code': 2016, u'moreInfo': u'http://docs.stormpath.com/errors/2016'  }

**Comment by rdegges** [comment]
Looking into this!

**Comment by rdegges** [comment]
Hmm... I can definitely reproduce this, but I'm having a hard time figuring out how this was introduced! I don't see any modifications to this code in a longgg time. I tried reverting recent changes to the `HttpExecutor` class, but still no luck.

I'm thinking about patching this manually for now, until I can get some time to analyze the underlying issue in more depth.

**Comment by rdegges** [comment]
Alright, going to cut a release with a fix in place.

**Comment by roengraft** [comment]
Thanks!
