### ISSUE TITLE
Exception raised during registration due to password requirements

### ISSUE THREAD

**Issue by miketheman** [stormpath/stormpath-flask#56]
```
127.0.0.1 - - [20/Nov/2015 08:04:25] "POST /register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "....python-2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "....python-2.7.10/lib/python2.7/site-packages/flask_stormpath/views.py", line 78, in register
    account = User.create(**data)
  File "....python-2.7.10/lib/python2.7/site-packages/flask_stormpath/models.py", line 101, in create
    _user = current_app.stormpath_manager.application.accounts.create({
  File "....python-2.7.10/lib/python2.7/site-packages/flask_stormpath/__init__.py", line 271, in application
    )[0]
  File "....python-2.7.10/lib/python2.7/site-packages/stormpath/resources/base.py", line 447, in __getitem__
    return self.__dict__['items'][idx]
IndexError: list index out of range
```

When user inputs password that does not conform to the current policy, a 500 error is raised, instead of passing back the problem, or even performing some input validation on the form.

**Comment by rdegges** [comment]
This is actually happening because the STORMPATH_APPLICATION setting you've defined has an Application that doesn't exist in Stormpath.

The Flask library lazily loads the Stormpath Application, so what's happening here is that when you hit this page and the Application is needed, it's looking for it in Stormpath, can't find it, and then errors out.

**Comment by miketheman** [comment]
Thanks, that solved it!

I got to this state due to the difference in https://devcenter.heroku.com/articles/stormpath#using-with-flask - specifically:

    app.config['STORMPATH_APPLICATION'] = environ.get('STORMPATH_URL')

**Comment by miketheman** [comment]
I guess a better error message of "application not found" might have had a different approach?

**Comment by rdegges** [comment]
You're totally right, btw! I've actually been planning on changing this for a while. I'm going to be spending a lot of time revamping this after the new year -- I'm currently wrapping up some work on our Node.js libraries, which should be finished soon =)

The next few things on the list:

- Make the library more magical (support all the stormpath core features).
- Change the loading strategy to be NON-LAZY (and throw better errors).
- Update the Heroku support to auto-detect STORMPATH_URL.
