### ISSUE TITLE
IndexError when trying to login, but Stormpath servers are experiencing issues

### ISSUE THREAD

**Issue by marianmazarovici** [stormpath/stormpath-flask#77]
> 2016-09-16 14:30:40,508 - __main__ - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1545, in handle_user_exception
    return handler(e)
  File "/Users/Salieri/PhpstormProjects/brightmatter-lengo/web.py", line 446, in internal_error
    raise error
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_stormpath/views.py", line 122, in login
    account = User.from_login(form.login.data, form.password.data)
  File "/usr/local/lib/python3.5/site-packages/flask_stormpath/models.py", line 125, in from_login
    _user = current_app.stormpath_manager.application.authenticate_account(login, password).account
  File "/usr/local/lib/python3.5/site-packages/flask_stormpath/__init__.py", line 271, in application
    )[0]
  File "/usr/local/lib/python3.5/site-packages/stormpath/resources/base.py", line 469, in __getitem__
    return self.__dict__['items'][idx]
IndexError: list index out of range

**Comment by rdegges** [comment]
It looks like one of two things happened here:

- Either stormpath was down, or
- Your Application name isn't correct.

**Comment by marianmazarovici** [comment]
Thank you for the reply, Randall. Is it possible to catch this and throw an exception with a meaningful message? Our users were unable to login for 2 days until we figured out where the problem comes from (in our case, it was the app name change).

**Comment by rdegges** [comment]
Yeah -- I've got this in progress right now in a new branch. The next major release will include smart error handling. Sorry about this :(
